Доработка кода
SergeyButGusaim/go-rest-api-homework pull request #1
Opened 2023-12-08 17:54 UTC by SergeyButGusaim

2023-12-09 10:49 UTC, just-musha requested changes
Привет! Спасибо за работу. Предлагаю обработать явно ошибки и оставить пустым тело запроса, где оставила комент. А так все супер, присылай правки и будет Approve

2023-12-09 10:49 UTC, just-musha commented on precode.go
> +	w.Write(resp)
Здесь возвращается полный список задач, до удаления, выглядит странно. По заданию не предполагается что delete что-то вернет в теле. Как насчет тело оставить его  в этом случае?

2023-12-09 10:49 UTC, just-musha commented on precode.go
> +	w.Write(resp)
Здесь давай явно обрабоатем ошибку - заигнорим через `_` или залогируем

2023-12-09 10:49 UTC, just-musha commented on precode.go
> +	w.Write(resp)
И здесь

2023-12-09 14:32 UTC, SergeyButGusaim commented on precode.go
> +	w.Write(resp)
Не понимаю, что именно и как предполагается заигнорировать или залогировать.

2023-12-09 14:33 UTC, SergeyButGusaim commented on precode.go
> +	w.Write(resp)
По заданию нужно:
При успешном выполнении запроса сервер должен вернуть статус 200 OK.
Я понял, что нужно http.StatusOK вывести, либо я не так понял тему.

2023-12-09 17:43 UTC, just-musha commented on precode.go
> +	w.Write(resp)
Метод Write возвращает error, речь о нем
`Write([][byte](https://pkg.go.dev/builtin#byte)) ([int](https://pkg.go.dev/builtin#int), [error](https://pkg.go.dev/builtin#error))`

И хочется показать в коде что ты об этом знаешь и например намеренно игнорируешь ошибку. Или логируешь
`_, err := w.Write(resp)`
`

2023-12-09 17:57 UTC, just-musha requested changes
Оставила в коде коменты, про обработку ошибки от Write, и ещё давай оставим запись тела ответа. С этими правками должно быть ок, предлагаю тебе убедиться через postman. И присылай правки

2023-12-09 17:57 UTC, just-musha commented on precode.go
> +	_, err := json.Marshal(tasks)
Ответ все-таки стоит записать. Проверь через postman как сейчас работает. В ответе должна приходить задача, которую ты запрашиваешь

2023-12-09 17:57 UTC, just-musha commented on precode.go
> +	w.Write(resp)
Все так говоришь. Просто есть 2 вещи - статус и тело ответа. Статус тут нужен, да - `w.WriteHeader(http.StatusOK)
`
А вот сам список задач - по заданию не нужно возвращаться для delete. Сравни с getTasks напрмер - для него сказано что нужно вернуть список задач. 

Рекомендую проверить через Postman, как сейчас выглядит ответ. Если что присылай ещё вопросы или обратись к наставникам за помощью.

2023-12-09 17:57 UTC, just-musha commented on precode.go
> +	_, err := json.Marshal(tasks)
И здесь тоже ответ нужно записать. Проверь через Postamn как сейчас работает, чтобы убедиться
И что будет если добавишь `w.Write(resp)`

2023-12-10 10:25 UTC, just-musha requested changes
Оставила в комментариях пример и пояснение, как можешь попробовать сделать. Попробуй поправить и присылай

2023-12-10 10:25 UTC, just-musha commented on precode.go
> +	if err != nil {
Это ошибка из строчки 90, она уже обработана на 91 строчке. С ней все ок. Этот блок кода не нужен

2023-12-10 10:25 UTC, just-musha commented on precode.go
> +	w.Write(resp)
Предлагаю что-то такое сделать, например:
```go
_, err := w.Write(resp) 
if err != nil {
    fmt.Println("error writing response: ", err.Error())
    return
}

2023-12-10 10:25 UTC, just-musha commented on precode.go
> +/*  Для POST
Отладочную информацию лучше не оставлять в коде

2023-12-10 14:32 UTC, just-musha approved these changes
Супер, спасибо! Принято. Надеюсь удалось разобраться почему именно так, если что пиши вопросы наставникам.

2023-12-11 16:40 UTC, merged